### ISSUE TITLE
(Question) How to use MetaQNL with multiple CPUs (Parallel processing)?

### ISSUE THREAD

**Issue by realharryhero** [princeton-vl/MetaQNL#21]
Hello (If you have time!),

The tool is quite clean (no warnings on the large SCAN dataset)! When I ran it, though, checking `top`, it only ran on one CPU. In the paper, there was some training MetaQNL on four CPUs; I also checked `train.jl --help` but parallel computing did not appear. Is there a way to run MetaQNL on multiple CPUs? Thank you!

**Comment by realharryhero** [comment]
(bump!)

**Comment by yangky11** [comment]
Sorry for the late response. 

The machine we used for running the experiments has four CPUs, though the codebase doesn't effectively use multiple CPUs. The most time-consuming part in training is calling the MaxSAT solver (Z3 by default). It may be possible to [run Z3 on multiple CPUs](https://theory.stanford.edu/~nikolaj/programmingz3.html#sec-cloning-solver-state-and-using-z3-from-multiple-threads), though we didn't experiment with it.

**Comment by realharryhero** [comment]
It seems there's a way to do this in C++, with `set_param("parallel.enable", true).` This is allowed after Z3 v4.8.1, and the current version of Z3.jl (v0.4.4) uses Z3 v4.12.1. Maybe adding the line `Z3.set_param("parallel.enable", true)` after `@info "Solving MAX-SAT..."` in [maxsat_solvers.jl](https://github.com/princeton-vl/MetaQNL/blob/main/src/optimization/maxsat_solvers.jl) may do the trick (but the SAT solver is so fast, as in 0.002 seconds fast, that it's not clear if or not it actually uses all 12 CPUs). Thank you!

(On the other hand, not directly related to the question but we can actually use GPUs for MaxSAT solving as well, using [a GPU SAT solver (ParaFROST)](https://github.com/muhos/ParaFROST) with a [MaxSAT solver](https://github.com/FlorentAvellaneda/EvalMaxSAT) that uses only SAT solving. There is also [this solver](https://arxiv.org/pdf/2402.03640) that directly uses a neural network to solve MaxSAT problems with GPUs, bridging discrete and continuous optimization. I think that’s pretty cool!)
